CREATE TABLE REGIONS (
    REGION_ID serial,
    REGION_NAME varchar(100) NOT NULL,
    PRIMARY KEY (REGION_ID)
);

CREATE TABLE PROJECTS (
    PROJECT_ID serial,
    PROJECT_NAME varchar(100) NOT NULL,
    CLIENT varchar(100) NOT NULL,
    REGION_ID int NOT NULL REFERENCES REGIONS(REGION_ID),
    ADDRESS varchar(100) NOT NULL,
    ZIPCODE int NOT NULL,
    CITY varchar(100) NOT NULL,
    MEGAWATTS float NOT NULL,
    BUDGET float NOT NULL,

    DATE_SURVEY date NOT NULL,
    DATE_CONTRACT date NOT NULL,
    DATE_START_CONSTRUCTION date NOT NULL,
    DATE_INTERCONNECTION date NOT NULL,
    DATE_OPERABLE date NOT NULL,
    DATE_COMMISSION date NOT NULL,

    SURVEY_COMPLETE bit NOT NULL,
    CONTRACT_SIGNED bit NOT NULL,
    CONSTRUCTION_STARTED bit NOT NULL,
    INTERCONNECTED bit NOT NULL,
    OPERABLE bit NOT NULL,
    COMMISSIONED bit NOT NULL,

    LINK_PLANS varchar(200) NOT NULL,
    LINK_CONTRACT varchar(200) NOT NULL,
    LINK_ENV_IMPACT_REPORT varchar(200) NOT NULL,
--    Max length notes 8000 characters
    NOTES varchar,
    PRIMARY KEY (PROJECT_ID)
);