CREATE TABLE REGIONS (
    REGION_ID serial,
    REGION_NAME varchar(100) NOT NULL,
    PRIMARY KEY (REGION_ID)
);

CREATE TABLE POSITIONS (
    POSITION_ID serial,
    POSITION varchar(100) NOT NULL,
    PRIMARY KEY (POSITION_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID serial,
    FIRST_NAME varchar(100) NOT NULL,
    LAST_NAME varchar(100) NOT NULL,
    PHONE_NUMBER varchar(100) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    REGION_ID int NOT NULL REFERENCES REGIONS(REGION_ID),
    POSITION_ID int NOT NULL REFERENCES POSITIONS(POSITION_ID),
    ASSIGNED_TO int,
    PRIMARY KEY (EMPLOYEE_ID)
);

--SELECT FIRST_NAME, LAST_NAME, POSITIONS.POSITION FROM EMPLOYEES
--LEFT JOIN POSITIONS ON EMPLOYEES.POSITION = POSITIONS.ID
--WHERE POSITIONS.ID = 1;