CREATE TABLE REGIONS (
    ID serial,
    REGION_NAME varchar(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE POSITIONS (
    ID serial,
    POSITION varchar(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEES (
    ID serial,
    FIRST_NAME varchar(100) NOT NULL,
    LAST_NAME varchar(100) NOT NULL,
    PHONE_NUMBER varchar(100) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    REGION int NOT NULL REFERENCES REGIONS(ID),
    POSITION int NOT NULL REFERENCES POSITIONS(ID),
    PRIMARY KEY (ID)
);

--SELECT FIRST_NAME, LAST_NAME, POSITIONS.POSITION FROM EMPLOYEES
--LEFT JOIN POSITIONS ON EMPLOYEES.POSITION = POSITIONS.ID
--WHERE POSITIONS.ID = 1;