CREATE TABLE POSITIONS (
  ID serial,
  POSITION varchar(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEES (
  ID serial,
  FIRST_NAME  varchar(100) NOT NULL,
  LAST_NAME varchar(100) NOT NULL,
  POSITION int(6) NOT NULL REFERENCES POSITIONS(ID),
  PRIMARY KEY (ID)
)